### ISSUE TITLE
Reload issue

### ISSUE THREAD

**Issue by Meghnawalkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1521]
While doing reload on in/out inventory its taking me to cash ledger

**Comment by mustafa-walkover** [comment]
done on test

**Comment by Meghnawalkover** [comment]
Same reload on JV its taking me to Dashboard

**Comment by mustafa-walkover** [comment]
done on test, please check

**Comment by walkover101** [comment]
It is not reloading on the same page while reloading from in & out from any module. Every time it through to the following page when I reload http://test.giddh.com/app/pages/inventory-in-out.

**Comment by walkover101** [comment]
JV is not resolved. It is getting back to dashboard after reloading the page.
