### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by Meghnawalkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1593]
Reload on JV taking to Dashboard. (have reported this many times)

**Comment by Meghnawalkover** [comment]
![Image 16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd1642b3dfe740013eebf3c/125516c66e82c728ace21e0d46c1999b2487c3f8d9abf301b44fff9e2c4533317346f62a26d5ba29e8402b54570c4caa41585641fff88d2ca5e42e6c981e5ab38532022d8c6853beb2901dbd0bbb258f498db2bc894ec8eb3426f5c6.png)

I am on onboarding but it not highlighting in left menu bar

**Comment by mustafa-walkover** [comment]
Done, please test @Meghnawalkover

**Comment by Meghnawalkover** [comment]
@rohit-walkover at the onboarding its still not highlighting in left menu bar

**Comment by Eagle-Giddh** [comment]
Working fine on test
